@startuml

title __INTERFACES's Class Diagram__\n

  namespace com.example.telecom.paris {
    namespace interfaces {
      interface com.example.telecom.paris.interfaces.Distance {
          {abstract} + getDistance()
      }
    }
  }
  

  namespace com.example.telecom.paris {
    namespace interfaces {
      interface com.example.telecom.paris.interfaces.Graph {
          {abstract} + getSuccessors()
          {abstract} + getVertex()
          {abstract} + getVertexes()
      }
    }
  }
  

  namespace com.example.telecom.paris {
    namespace interfaces {
      interface com.example.telecom.paris.interfaces.MinDistance {
          {abstract} + getMinDistance()
          {abstract} + getMinDistanceVertex()
          {abstract} + setMinDistance()
      }
    }
  }
  

  namespace com.example.telecom.paris {
    namespace interfaces {
      interface com.example.telecom.paris.interfaces.ProcessedVertexesSet {
          {abstract} + add()
          {abstract} + contains()
      }
    }
  }
  

  namespace com.example.telecom.paris {
    namespace interfaces {
      interface com.example.telecom.paris.interfaces.ShortestPaths {
          {abstract} + getShortestPath()
          {abstract} + setPrevious()
      }
    }
  }
  

  namespace com.example.telecom.paris {
    namespace interfaces {
      interface com.example.telecom.paris.interfaces.Vertex {
          {abstract} + getLabel()
          {abstract} + getSuccessors()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
